apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sampleginx
    day: friday
  name: sampleginx
  namespace: auto
  annotations:
    state: testing
    today: thursday
    almost: done
    weather: rainy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sampleginx
        test: automation
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
